spring:
  application:
    name: rix_markets_configuration_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rixonmathew/rvm_config
server:
  port: 8888
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
